/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author 23040
 */
public class TelaCalculadora extends javax.swing.JFrame {

    double memory;
    double firstNumber;
    double secondNumber;
    double result;
    String operation;
    
    
    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
        
        List<JButton> buttons = getButtons(getContentPane());
        for(JButton button : buttons){
            button.setFont(new Font("Arial", Font.PLAIN, 30));
        }
        
        textScreen.setFont(new Font("Arial", Font.PLAIN, 30));
    }
    
    public List<JButton> getButtons(Container container){
        List<JButton> buttons = new ArrayList<>();
        Component[] components = container.getComponents();
        
        for(Component component : components){
            if(component instanceof JButton){
                buttons.add((JButton) component);
            }
        }
        return buttons;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textScreen = new javax.swing.JTextField();
        buttonMemoryMore = new javax.swing.JButton();
        buttonMemoryLess = new javax.swing.JButton();
        buttonMemoryReturn = new javax.swing.JButton();
        buttonMemoryClear = new javax.swing.JButton();
        buttonMoreLess = new javax.swing.JButton();
        buttonDivision = new javax.swing.JButton();
        buttonMulti = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        buttonSeven = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonLess = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonSum = new javax.swing.JButton();
        buttonOne = new javax.swing.JButton();
        buttonEquaus = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonPoint = new javax.swing.JButton();
        buttonZero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        textScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textScreenActionPerformed(evt);
            }
        });

        buttonMemoryMore.setBackground(new java.awt.Color(253, 73, 0));
        buttonMemoryMore.setText("M+");
        buttonMemoryMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemoryMoreActionPerformed(evt);
            }
        });

        buttonMemoryLess.setBackground(new java.awt.Color(253, 73, 0));
        buttonMemoryLess.setText("M-");
        buttonMemoryLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemoryLessActionPerformed(evt);
            }
        });

        buttonMemoryReturn.setBackground(new java.awt.Color(253, 73, 0));
        buttonMemoryReturn.setText("MR");
        buttonMemoryReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemoryReturnActionPerformed(evt);
            }
        });

        buttonMemoryClear.setBackground(new java.awt.Color(253, 73, 0));
        buttonMemoryClear.setText("MC");
        buttonMemoryClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMemoryClearActionPerformed(evt);
            }
        });

        buttonMoreLess.setBackground(new java.awt.Color(253, 73, 0));
        buttonMoreLess.setText("+/-");
        buttonMoreLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMoreLessActionPerformed(evt);
            }
        });

        buttonDivision.setBackground(new java.awt.Color(253, 73, 0));
        buttonDivision.setText("/");
        buttonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivisionActionPerformed(evt);
            }
        });

        buttonMulti.setBackground(new java.awt.Color(253, 73, 0));
        buttonMulti.setText("x");
        buttonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiActionPerformed(evt);
            }
        });

        buttonClear.setBackground(new java.awt.Color(253, 73, 0));
        buttonClear.setText("c");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonNine.setBackground(new java.awt.Color(0, 0, 0));
        buttonNine.setText("9");
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });

        buttonSeven.setBackground(new java.awt.Color(0, 0, 0));
        buttonSeven.setText("7");
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });

        buttonEight.setBackground(new java.awt.Color(0, 0, 0));
        buttonEight.setText("8");
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });

        buttonLess.setBackground(new java.awt.Color(253, 73, 0));
        buttonLess.setText("-");
        buttonLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLessActionPerformed(evt);
            }
        });

        buttonSix.setBackground(new java.awt.Color(0, 0, 0));
        buttonSix.setText("6");
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });

        buttonFive.setBackground(new java.awt.Color(0, 0, 0));
        buttonFive.setText("5");
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });

        buttonFour.setBackground(new java.awt.Color(0, 0, 0));
        buttonFour.setText("4");
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });

        buttonSum.setBackground(new java.awt.Color(253, 73, 0));
        buttonSum.setText("+");
        buttonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSumActionPerformed(evt);
            }
        });

        buttonOne.setBackground(new java.awt.Color(0, 0, 0));
        buttonOne.setText("1");
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });

        buttonEquaus.setBackground(new java.awt.Color(253, 73, 0));
        buttonEquaus.setText("=");
        buttonEquaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEquausActionPerformed(evt);
            }
        });

        buttonTwo.setBackground(new java.awt.Color(0, 0, 0));
        buttonTwo.setText("2");
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });

        buttonThree.setBackground(new java.awt.Color(0, 0, 0));
        buttonThree.setText("3");
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });

        buttonPoint.setBackground(new java.awt.Color(0, 0, 0));
        buttonPoint.setText(".");
        buttonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPointActionPerformed(evt);
            }
        });

        buttonZero.setBackground(new java.awt.Color(0, 0, 0));
        buttonZero.setText("0");
        buttonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZeroActionPerformed(evt);
            }
        });

        jLabel1.setText("Produzido por Pedro Henrique");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textScreen)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMemoryMore, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMemoryLess, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMemoryReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMoreLess, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLess, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEquaus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMemoryMore, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMemoryLess, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMemoryReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMoreLess, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLess, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonEquaus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMemoryMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemoryMoreActionPerformed
        double memoryResult;
        String resultFomatted;
        double memoryMore = Double.parseDouble(textScreen.getText());
        memoryResult = memoryMore + memory ;
        resultFomatted = String.format("%.2f", memoryResult);
        textScreen.setText(resultFomatted);
        memory = memoryResult;
    }//GEN-LAST:event_buttonMemoryMoreActionPerformed

    private void buttonMemoryReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemoryReturnActionPerformed
        String resultFomatted = Double.toString(memory);
        textScreen.setText(resultFomatted);
    }//GEN-LAST:event_buttonMemoryReturnActionPerformed

    private void buttonMemoryLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemoryLessActionPerformed
        double memoryResult;
        String resultFomatted;
        double memoryMore = Double.parseDouble(textScreen.getText());
        memoryResult = memory - memoryMore ;
        resultFomatted = String.format("%.2f", memoryResult);
        textScreen.setText(resultFomatted);
        memory = memoryResult;
    }//GEN-LAST:event_buttonMemoryLessActionPerformed

    private void buttonMemoryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMemoryClearActionPerformed
        memory = 0;
        textScreen.setText("");
    }//GEN-LAST:event_buttonMemoryClearActionPerformed

    private void buttonMoreLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMoreLessActionPerformed
        if(operation != null){
            secondNumber = Double.parseDouble(textScreen.getText());
            secondNumber = secondNumber * (-1);
            String teste = Double.toString(secondNumber);
            textScreen.setText(teste);
        }else{
            firstNumber = Double.parseDouble(textScreen.getText());
            firstNumber = firstNumber * (-1);
            String teste = Double.toString(firstNumber);
            textScreen.setText(teste);
        }
    }//GEN-LAST:event_buttonMoreLessActionPerformed

    private void buttonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivisionActionPerformed
        if(!textScreen.getText().equals("")){
            firstNumber = Double.parseDouble(textScreen.getText());
            textScreen.setText("");
            operation = "/";
        }
    }//GEN-LAST:event_buttonDivisionActionPerformed

    private void buttonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiActionPerformed
        if(!textScreen.getText().equals("")){
            firstNumber = Double.parseDouble(textScreen.getText());
            textScreen.setText("");
            operation = "*";
        }
    }//GEN-LAST:event_buttonMultiActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        textScreen.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNineActionPerformed
        String input;
        input = textScreen.getText() + buttonNine.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonNineActionPerformed

    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed
        String input;
        input = textScreen.getText() + buttonSeven.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonSevenActionPerformed

    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed
        String input;
        input = textScreen.getText() + buttonEight.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonEightActionPerformed

    private void buttonLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLessActionPerformed
        if(!textScreen.getText().equals("")){
            firstNumber = Double.parseDouble(textScreen.getText());
            textScreen.setText("");
            operation = "-";
        }
    }//GEN-LAST:event_buttonLessActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
        String input;
        input = textScreen.getText() + buttonSix.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonSixActionPerformed

    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
        String input;
        input = textScreen.getText() + buttonFive.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonFiveActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
        String input;
        input = textScreen.getText() + buttonFour.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonFourActionPerformed

    private void buttonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSumActionPerformed
        if(!textScreen.getText().equals("")){
            firstNumber = Double.parseDouble(textScreen.getText());
            textScreen.setText("");
            operation = "+";
        }
    }//GEN-LAST:event_buttonSumActionPerformed

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        String input;
        input = textScreen.getText() + buttonOne.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonOneActionPerformed

    private void buttonEquausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEquausActionPerformed
        if(operation != null){
            String resultFomatted;
            secondNumber = Double.parseDouble(textScreen.getText());
                switch (operation) {
                case "+":
                    result = firstNumber + (secondNumber);
                    resultFomatted = String.format("%.2f", result);
                    textScreen.setText(resultFomatted);
                    memory = result;
                    break;
                case "-":
                    result = firstNumber - secondNumber;
                    resultFomatted = String.format("%.2f", result);
                    textScreen.setText(resultFomatted);
                    memory = result;
                    break;
                case "*":
                    result = firstNumber * secondNumber;
                    resultFomatted = String.format("%.2f", result);
                    textScreen.setText(resultFomatted);
                    memory = result;
                    break;
                case "/":
                    result = firstNumber / secondNumber;
                    resultFomatted = String.format("%.4f", result);
                    textScreen.setText(resultFomatted);
                    memory = result;
                    break;
                default:
                    throw new AssertionError();
                }
        }    
    }//GEN-LAST:event_buttonEquausActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        String input;
        input = textScreen.getText() + buttonTwo.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed
        String input;
        input = textScreen.getText() + buttonThree.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonThreeActionPerformed

    private void buttonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPointActionPerformed
        String input;
        input = textScreen.getText() + buttonPoint.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonPointActionPerformed

    private void buttonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZeroActionPerformed
        String input;
        input = textScreen.getText() + buttonZero.getText();
        textScreen.setText(input);
    }//GEN-LAST:event_buttonZeroActionPerformed

    private void textScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textScreenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDivision;
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonEquaus;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonLess;
    private javax.swing.JButton buttonMemoryClear;
    private javax.swing.JButton buttonMemoryLess;
    private javax.swing.JButton buttonMemoryMore;
    private javax.swing.JButton buttonMemoryReturn;
    private javax.swing.JButton buttonMoreLess;
    private javax.swing.JButton buttonMulti;
    private javax.swing.JButton buttonNine;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonPoint;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonSum;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JButton buttonZero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textScreen;
    // End of variables declaration//GEN-END:variables
}
